server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://k5d104.p.ssafy.io/"

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: local