server:
  port: 8000

eureka:
  client:
    #eureka 서버에 등록 가능 설정
    register-with-eureka: true
    #외부에서 검색 가능한 형태로 만듬
    fetch-registry: true
    #eureka 엔드포인트에 현재 마이크로서비스를 등록
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true   #추가
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
#      routes:
#        - id: test-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/test/**
#        - id: second-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second-service/**